version: '2'

services:
  postgres:
    image: postgres:10.3
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tippspiel
    ports:
      - 5432:5432

